# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Ensure alias-tips is available
ALIAS_TIPS_LINK="$ZSH/plugins/alias-tips"
if [ ! -e "$ALIAS_TIPS_LINK" ]; then
    echo "Link alias-tips in $ALIAS_TIPS_LINK"
    ln -s "$HOME/.my/vendor/alias-tips" "$ALIAS_TIPS_LINK"
fi
unset ALIAS_TIPS_LINK

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git battery brew golang macos pip python virtualenv autojump git-flow adb npm yarn alias-tips)
# autoenv: automaticly execs script on changing dir (.env file)
# cp: cp with progression "cpv"

source $ZSH/oh-my-zsh.sh

##         ##
## General ##
##         ##

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export PATH="$HOME/.rvm/bin:$HOME/bin:/usr/local/share/npm/bin:$PATH"

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history


##              ##
## Prompt theme ##
##              ##

# Disable part for oh-my-zsh prompt
# DISABLE_OH_MY_ZSH=1
if [ -n "$DISABLE_OH_MY_ZSH" ];then

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
#eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

#add 28/07/2011
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BDésolé, pas de résultats pour : %d%b'
zstyle ':completion:*' menu select=2
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s

zstyle ':completion:*:rm:*' ignore-line yes
#zstyle ':completion:*:mv:*' ignore-line yes
#zstyle ':completion:*:cp:*' ignore-line yes

#bash completion
autoload -U bashcompinit
bashcompinit

# End DISABLE_OH_MY_ZSH
fi


##        ##
## Ending ##
##        ##

source "$HOME/.my/dotfiles.sh"

