###
### Starship configuration.
### See https://starship.rs/config/ for customization.
###

function init_starship {
  # Install if not loaded + missing in path
  if [ -z "$STARSHIP_SHELL" ] && ! command -v starship > /dev/null; then
    echo ">> Install starship"
    case "$OSTYPE" in
      darwin*) brew install starship ;;
      *)       curl -sS https://starship.rs/install.sh | sh ;;
    esac
  fi

  generate_starship_config
}

function generate_starship_config {
  local src="$DOTFILES/sh/starship.sh"
  local target="$HOME/.config/starship.toml"

  # Pin the generated config to the hash of this script so it is rebuilt only
  # when starship.sh actually changes. Stored in local/ (machine-only files).
  local hash cached
  hash=$(md5 -q "$src" 2>/dev/null || md5sum "$src" 2>/dev/null | cut -d' ' -f1)
  cached="$DOTFILES/local/starship.$hash.toml"

  if [ ! -f "$cached" ]; then
    mkdir -p "$DOTFILES/local"
    local success_symbol error_symbol
    case "$OSTYPE" in
      darwin*) success_symbol='🍏 ➜ '; error_symbol='🍎 ➜ ' ;;
      linux*)  success_symbol='🐧 ➜ '; error_symbol='🧨 ➜ ' ;;
      *)       success_symbol='➜ ';    error_symbol='➜ ' ;;
    esac
    # Single atomic write: build a temp file, then rename it into place so
    # concurrent shell startups can never observe a half-written config.
    local tmp="$cached.tmp.$$.$RANDOM"
    cat > "$tmp" <<EOF
add_newline = true

[git_branch]
symbol = ''
[git_commit]
disabled = true
[git_state]
disabled = true
[git_status]
disabled = true

[java]
style="bold red"

[character]
success_symbol = '$success_symbol'
error_symbol = '$error_symbol'
EOF
    mv -f "$tmp" "$cached"
    # Drop configs generated by previous versions of this script.
    find "$DOTFILES/local" -maxdepth 1 -name 'starship.*.toml' ! -name "starship.$hash.toml" -delete 2>/dev/null
  fi

  # Point starship at the pinned config (cheap, idempotent symlink refresh).
  mkdir -p "$HOME/.config"
  if [ "$(readlink "$target" 2>/dev/null)" != "$cached" ]; then
    ln -sfn "$cached" "$target"
  fi
}

# https://starship.rs/guide/#getting-started
case $SHELL in
  */zsh)  init_starship && eval "$(starship init zsh)" ;;
  */bash) init_starship && eval "$(starship init bash)" ;;
  *)      echo "Unsupported shell, cannot load starship."
esac

unset -f init_starship
unset -f generate_starship_config
